apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-kubernetes-component
  annotations:
    backstage.io/kubernetes-id: my-kubernetes-component
spec:
  type: service
  owner: my-team
  lifecycle: production
